apiVersion: v1
kind: Service
metadata:
  name: camera-collector-service
  namespace: default
spec:
  selector:
    app: camera-collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
